//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainControl.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.125 的本地化字符串。
        /// </summary>
        internal static string CB_IP_Num1 {
            get {
                return ResourceManager.GetString("CB_IP_Num1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.126 的本地化字符串。
        /// </summary>
        internal static string CB_IP_Num2 {
            get {
                return ResourceManager.GetString("CB_IP_Num2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.127 的本地化字符串。
        /// </summary>
        internal static string CB_IP_Num3 {
            get {
                return ResourceManager.GetString("CB_IP_Num3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.128 的本地化字符串。
        /// </summary>
        internal static string CB_IP_Num4 {
            get {
                return ResourceManager.GetString("CB_IP_Num4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5000 的本地化字符串。
        /// </summary>
        internal static string CB_Port_Num1 {
            get {
                return ResourceManager.GetString("CB_Port_Num1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5000 的本地化字符串。
        /// </summary>
        internal static string CB_Port_Num2 {
            get {
                return ResourceManager.GetString("CB_Port_Num2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5000 的本地化字符串。
        /// </summary>
        internal static string CB_Port_Num3 {
            get {
                return ResourceManager.GetString("CB_Port_Num3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5000 的本地化字符串。
        /// </summary>
        internal static string CB_Port_Num4 {
            get {
                return ResourceManager.GetString("CB_Port_Num4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.131 的本地化字符串。
        /// </summary>
        internal static string GamePC_IP_Num1 {
            get {
                return ResourceManager.GetString("GamePC_IP_Num1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.132 的本地化字符串。
        /// </summary>
        internal static string GamePC_IP_Num2 {
            get {
                return ResourceManager.GetString("GamePC_IP_Num2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.133 的本地化字符串。
        /// </summary>
        internal static string GamePC_IP_Num3 {
            get {
                return ResourceManager.GetString("GamePC_IP_Num3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.134 的本地化字符串。
        /// </summary>
        internal static string GamePC_IP_Num4 {
            get {
                return ResourceManager.GetString("GamePC_IP_Num4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10000 的本地化字符串。
        /// </summary>
        internal static string GamePC_Port_Num1 {
            get {
                return ResourceManager.GetString("GamePC_Port_Num1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10000 的本地化字符串。
        /// </summary>
        internal static string GamePC_Port_Num2 {
            get {
                return ResourceManager.GetString("GamePC_Port_Num2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10000 的本地化字符串。
        /// </summary>
        internal static string GamePC_Port_Num3 {
            get {
                return ResourceManager.GetString("GamePC_Port_Num3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10000 的本地化字符串。
        /// </summary>
        internal static string GamePC_Port_Num4 {
            get {
                return ResourceManager.GetString("GamePC_Port_Num4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.130 的本地化字符串。
        /// </summary>
        internal static string MainControlPC_IP {
            get {
                return ResourceManager.GetString("MainControlPC_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10000 的本地化字符串。
        /// </summary>
        internal static string MainControlPC_Port {
            get {
                return ResourceManager.GetString("MainControlPC_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.120 的本地化字符串。
        /// </summary>
        internal static string PLC_IP {
            get {
                return ResourceManager.GetString("PLC_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5000 的本地化字符串。
        /// </summary>
        internal static string PLC_Port {
            get {
                return ResourceManager.GetString("PLC_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.161 的本地化字符串。
        /// </summary>
        internal static string Projector_IP_Dev1Num1 {
            get {
                return ResourceManager.GetString("Projector_IP_Dev1Num1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.162 的本地化字符串。
        /// </summary>
        internal static string Projector_IP_Dev1Num2 {
            get {
                return ResourceManager.GetString("Projector_IP_Dev1Num2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.163 的本地化字符串。
        /// </summary>
        internal static string Projector_IP_Dev2Num1 {
            get {
                return ResourceManager.GetString("Projector_IP_Dev2Num1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.164 的本地化字符串。
        /// </summary>
        internal static string Projector_IP_Dev2Num2 {
            get {
                return ResourceManager.GetString("Projector_IP_Dev2Num2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.165 的本地化字符串。
        /// </summary>
        internal static string Projector_IP_Dev3Num1 {
            get {
                return ResourceManager.GetString("Projector_IP_Dev3Num1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.166 的本地化字符串。
        /// </summary>
        internal static string Projector_IP_Dev3Num2 {
            get {
                return ResourceManager.GetString("Projector_IP_Dev3Num2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.167 的本地化字符串。
        /// </summary>
        internal static string Projector_IP_Dev4Num1 {
            get {
                return ResourceManager.GetString("Projector_IP_Dev4Num1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.0.168 的本地化字符串。
        /// </summary>
        internal static string Projector_IP_Dev4Num2 {
            get {
                return ResourceManager.GetString("Projector_IP_Dev4Num2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4352 的本地化字符串。
        /// </summary>
        internal static string Projector_Port_Dev1Num1 {
            get {
                return ResourceManager.GetString("Projector_Port_Dev1Num1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4352 的本地化字符串。
        /// </summary>
        internal static string Projector_Port_Dev1Num2 {
            get {
                return ResourceManager.GetString("Projector_Port_Dev1Num2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4352 的本地化字符串。
        /// </summary>
        internal static string Projector_Port_Dev2Num1 {
            get {
                return ResourceManager.GetString("Projector_Port_Dev2Num1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4352 的本地化字符串。
        /// </summary>
        internal static string Projector_Port_Dev2Num2 {
            get {
                return ResourceManager.GetString("Projector_Port_Dev2Num2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4352 的本地化字符串。
        /// </summary>
        internal static string Projector_Port_Dev3Num1 {
            get {
                return ResourceManager.GetString("Projector_Port_Dev3Num1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4352 的本地化字符串。
        /// </summary>
        internal static string Projector_Port_Dev3Num2 {
            get {
                return ResourceManager.GetString("Projector_Port_Dev3Num2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4352 的本地化字符串。
        /// </summary>
        internal static string Projector_Port_Dev4Num1 {
            get {
                return ResourceManager.GetString("Projector_Port_Dev4Num1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4352 的本地化字符串。
        /// </summary>
        internal static string Projector_Port_Dev4Num2 {
            get {
                return ResourceManager.GetString("Projector_Port_Dev4Num2", resourceCulture);
            }
        }
    }
}
